### ISSUE TITLE
Content of the site has disappeared, now looking like a fresh install...

### ISSUE THREAD

**Issue by raphraph** [YunoHost-Apps/yellow_ynh#26]
### Describe the bug

I had installed a Yellow site on my raspberryPI, the site was not fhinished and I did not take a look at it for a couple of months (approximately).

I wanted to work again on the site and I discovered that the content of my Yellow site has disappeared, I now fall on the  fresh install page...

I searched in my raspberryPI if I could find the site content somewhere else than in `/var/www/yellow/content/` but nothing comes out.

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: *4.3.6.3 (stable)*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

My yunohost instance has probably been upgraded between last time the site was working and now. Concerning the Yellow app I don't know if I upgraded it or not (can't remember but maybe this information can be found in logs ?).

The Yellow app version is now 0.8.20\~ynh1 and I see that there is an upgrade available for 0.8.20\~ynh2

### Steps to reproduce

I don't know...

### Expected behavior

Content not disappearing 😥

### Logs

I can provide logs if needed, but I don't know which logs can be interesting in this case (I'm not running into an error...).

**Comment by raphraph** [comment]
Further investigating I finally found an automatic (? thanks Yunohost !!) backup of the Yellow app before an upgrade:

```
ID yellow-pre-upgrade1
Crée le 15 juin 2022 à 10:29:19
Taille 2 MB
Chemin /home/yunohost.backup/archives/yellow-pre-upgrade1.tar
Version 0.8.18~ynh1
```

and this backup contains my site content, so it is not lost...

But apparently something went wrong with this upgrade ? I suppose...

**Comment by ericgaspar** [comment]
closing with #31
