### ISSUE TITLE
Add the topic datenstrom-yellow

### ISSUE THREAD

**Issue by markseu** [YunoHost-Apps/yellow_ynh#5]
Hello !

Here's a tip from the Datenstrom Yellow maintainers: Please add the topic `datenstrom-yellow` to your repository. https://github.com/topics/datenstrom-yellow

Thanks for maintaining the YunoHost integration, this is much appreciated. 👍

**Comment by ericgaspar** [comment]
Sorry for the late response. i just saw you post... I just added `datenstrom-yellow`in the topic.
